"use client"

import './globals.css'
import { ThemeProvider } from '@mui/material/styles'
import CssBaseline from '@mui/material/CssBaseline'
import muiTheme from './core/muiTheme'
import StyledComponentsRegistry from './lib/registry'
import { SessionProvider } from "next-auth/react"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SessionProvider refetchInterval={600}>
          <ThemeProvider theme={muiTheme}>
            <CssBaseline />
            <StyledComponentsRegistry>
              <>
                {children}
              </>
            </StyledComponentsRegistry>
          </ThemeProvider>
          </SessionProvider>
      </body>
    </html>
  )
}
